---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Viscoop v0.0.0.9000

<!-- badges: start -->
<!-- badges: end -->

Viscoop é um dashboard que reúne diversas informações sobre as cooperativas brasileiras disponíveis de forma pública em diversos bancos de dados nacionais, como do [Banco Central do Brasil - Bacen](https://www.bcb.gov.br/), da [Relação Aanual de Informações Sociais - RAIS](http://pdet.mte.gov.br/microdados-rais-e-caged?_ga=2.76313365.1278749075.1612490536-1284000383.1612490536), da [Receita Federal do Brasil - RFB](https://www.gov.br/receitafederal/pt-br/assuntos/orientacao-tributaria/cadastros/consultas/dados-publicos-cnpj) e outros. 

Também será feito o cruzamento dos dados e algumas análises estatísticas.

## Site
https://rtheodoro.shinyapps.io/viscoop


## Objetivo do projeto

O objetivo deste projeto é, além de fornecer formas fáceis de visualização de informações sobre cooperativas brasileiras, é aprendizado. Tanto para os desenvolvedores do projeto quanto para o público que acessa.

Para estimular o aprendizado e garantir a transparência das informações, este projeto está disponível inteiramente no [GitHub](https://github.com/rtheodoro/Viscoop). Isso possibilita a conferência de nossos cálculos, adaptação para outros projetos e que os interessados possam utilizar o código onde desejar (desde que citada a fonte, conforme [licença CC BY 4.0](https://github.com/rtheodoro/Viscoop/blob/main/LICENSE.md)).


## Sobre as bases

### Banco Central do Brasil - Bacen
### Relação Aanual de Informações Sociais - RAIS
### Receita Federal do Brasil - RFB


## Outras informações

Todo o projeto foi feito no programa `R()`, utilizando os pacotes `shiny()` e `golem()`. Para aprender mais sobre, segue um vídeo muito bom da [curso-r no LatinR](https://www.youtube.com/watch?v=fiaZgGqcubc).

Projeto apenas iniciado, falta muuuuuuuuuuito.
